articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.home, name='home'),
]

richtext/urls.py
from django.urls import path
from . import views

app_name = 'richtext'

urlpatterns = [
    path('post', views.post, name='post'),
]

text_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path(r'mdeditor/', include('mdeditor.urls')),
    path('richtext/', include('richtext.urls')),
]

articles/models.py
from django.db import models
from mdeditor.fields import MDTextField

class Articles(models.Model):
    title = models.CharField(max_length=255)
    content = MDTextField()

richtext/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = RichTextField()

articles/forms.py
from django import forms
from django.db.models import fields
from .models import Articles

class CreateArticleForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')
    description = forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder':'Description', 'rows': 10, 'cols': 60}))

    class Meta:
        model = Articles
        fields = ('title', 'description', )

richtext/forms.py
from django import forms
from .models import Post
from ckeditor.widgets import CKEditorWidget

class PostForm(forms.ModelForm):
    title = forms.CharField(label='タイトル')
    content = forms.CharField(label='内容', widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = '__all__'

articles/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib import messages

def home(request):
    create_article_form = forms.CreateArticleForm(request.POST or None)
    if create_article_form.is_valid():
        create_article_form.save()
        messages.success(request, '投稿しました')
    return render(
        request, 'articles/home.html', context={
            'create_article_form': create_article_form,
        }
    )

richtext/views.py
from django.shortcuts import render,redirect
from .forms import PostForm
from django.contrib import messages

def post(request):
    post_form = PostForm(request.POST or None)
    if post_form.is_valid():
        post_form.save()
        messages.success(request, '成功しました')
    return render(request, 'richtext/post.html', context={
        'post_form': post_form,
    })

templates/articles/home.html
{% extends 'base.html' %}
{% block content %}
<h3>ホーム</h3>
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} " role="alert">
            {{ message.message }}
        </div>
    {% endfor %}
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ create_article_form.as_p }}
    <input class="btn btn-outline-primary" type="submit" value="投稿">
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <title>TextTest</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'articles:home' %}">TextTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'articles:home' %}">ホーム</a>
                    </li>
                </ul>
            </div>
        </nav>
    {% block content %}{% endblock %}
    {% block javascript %}{% endblock %}
    </body>
</html>

templates/richtext/post.html
{% extends 'base.html' %}
{% block content %}
<h3>ホーム</h3>
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} " role="alert">
            {{ message.message }}
        </div>
    {% endfor %}
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ post_form.as_p }}
    <input class="btn btn-outline-primary" type="submit" value="投稿">
</form>
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}